const INIT_NAME_STATE = "";
const INIT_EMAIL_STATE = "";
const INIT_SUBJECT_STATE = "";
const INIT_MESSAGE_STATE = "";
const INIT_STATUS_MESSAGE_STATE = { status: null, message: "" };

export { INIT_NAME_STATE, INIT_EMAIL_STATE, INIT_SUBJECT_STATE, INIT_MESSAGE_STATE, INIT_STATUS_MESSAGE_STATE };
